### ISSUE TITLE
Database Operational Error

### ISSUE THREAD

**Issue by scorpionhiccup** [mfazal/vitals#1]
Can u pls, share the SOS.db file file with the sqlite3 defined?

**Comment by Guruprasad93** [comment]
There's just one database (app.db), which has multiple tables. In order to access the tables on sqlite3; Try these commands:
sqlite3
.open app.db
.tables {You will view all tables in app.db}

If you have a problem with committing data into the db - you could run db_create.py and db_migrate.py to create/migrate the database. Then run.py and bash vitals.sh.

**Comment by mfazal** [comment]
app.db sqlite3 database file is not uploaded as it is ignored based on .gitignore file.

Updated the README file to show how to initialise the DB.
